### ISSUE TITLE
Change url

### ISSUE THREAD

**Issue by anthager** [istodaymeatballsday/twitter_bot#1]
Change api url to https://api.istodaymeatballsday.com

**Comment by joakimthorell** [comment]
> Change api url to https://istodaymeatballsday.com/api

Requests to this api gives:
```
{"message":"Missing Authentication Token"}
```
Please provide information on how to use

**Comment by anthager** [comment]
Sorry, the api was redeployed after this issue was submitted. See change

**Comment by joakimthorell** [comment]
Thank you, the current version of the bot is using https://api.istodaymeatballsday.com. Please reopen if there is still an issue
